/*

Background

We've had challenges before on Fibonacci coding and Zeckendorf representation.
These representations follow naturally from Zeckendorf's theorem, which states that every positive integer can be represented uniquely as the sum of one or more distinct, non-consecutive Fibonacci numbers.
For example:

64171=55+8+1=F10+F6+F2=144+21+5+1=F12+F8+F5+F2

where Fi is the i-th Fibonacci number.

What is Fibonacci multiplication?

Extending this concept, Donald Knuth defined "circle multiplication" (the Fibonacci product) on two postive integers a and b as follows.

First assume

ab=∑i=[0,n]F[ci] where ci≥2=∑i=[0,m] F[di] where di≥2

Then we define the Fibonacci product like so:

a∘b=∑i=0n∑j=[0,m]F[ci]+[dj]

See Knuth's original article (pdf) or the Wikipedia entry for more.

Here is a worked example from the Wikipedia page:

242∘4=F3=F4+F2=F3+4+F3+2=F7+F5=13+5=18

As an interesting aside not directly related to the challenge, it has been shown that the Fibonacci product:

    can be interpreted as the usual multiplication in a multiplicatively closed subset of the ring Z[ϕ]

    of algebraic integers generated by the "golden ratio".

Task

Given two positive integers as input, return their Fibonacci product as defined in the section above.

This is code-golf and standard site rules apply.
Test Cases

1 1 -> 3
1 2 -> 5
1 5 -> 13
2 1 -> 5
2 4 -> 18
4 1 -> 11
4 4 -> 40
4 9 -> 87
7 1 -> 18 
7 2 -> 29
7 9 -> 141
9 9 -> 189

*/

#include <assert.h>
#include <stdio.h>

typedef unsigned long long uvlong;

/*

https://en.wikipedia.org/wiki/Zeckendorf%27s_theorem#Fibonacci_multiplication
https://www.sciencedirect.com/science/article/pii/0893965989900785

*/

uvlong
fibmul(uvlong m, uvlong n)
{
	static const double phi = 1.6180339887498948482045868343656381177203091798057628621354486227052604628189024497072072041893911374;

	uvlong pm, pn;

	pm = (m + 1) / phi;
	pn = (n + 1) / phi;
	return (m * n) + (pm * n) + (m * pn);
}

int
main(void)
{
	assert(fibmul(1, 1) == 3);
	assert(fibmul(1, 2) == 5);
	assert(fibmul(1, 5) == 13);
	assert(fibmul(2, 1) == 5);
	assert(fibmul(2, 4) == 18);
	assert(fibmul(4, 1) == 11);
	assert(fibmul(4, 4) == 40);
	assert(fibmul(4, 9) == 87);
	assert(fibmul(7, 1) == 18);
	assert(fibmul(7, 2) == 29);
	assert(fibmul(7, 9) == 141);
	assert(fibmul(9, 9) == 189);

	return 0;
}
