/*

The Feynman Challenge Cipher #1 is as follows:

MEOTAIHSIBRTEWDGLGKNLANEAINOEEPEYST
NPEUOOEHRONLTIROSDHEOTNPHGAAETOHSZO
TTENTKEPADLYPHEODOWCFORRRNLCUEEEEOP
GMRLHNNDFTOENEALKEHHEATTHNMESCNSHIR
AETDAHLHEMTETRFSWEDOEOENEGFHETAEDGH
RLNNGOAAEOCMTURRSLTDIDOREHNHEHNAYVT
IERHEENECTRNVIOUOEHOTRNWSAYIFSNSHOE
MRTRREUAUUHOHOOHCDCHTEEISEVRLSKLIHI
IAPCHRHSIHPSNWTOIISISHHNWEMTIEYAFEL
NRENLEERYIPHBEROTEVPHNTYATIERTIHEEA
WTWVHTASETHHSDNGEIEAYNHHHNNHTW
The solution is described as:

It is a simple transposition cipher: split the text into 5-column pieces, then read from lower right upward. What results are the opening lines of Chaucer's Canterbury Tales in Middle English.

Which is:

WHANTHATAPRILLEWITHHISSHOURESSOOTET
HEDROGHTEOFMARCHHATHPERCEDTOTHEROOT
EANDBATHEDEVERYVEYNEINSWICHLICOUROF
WHICHVERTUENGENDREDISTHEFLOURWHANZE
PHIRUSEEKWITHHISSWEETEBREFTHINSPIRE
DHATHINEVERYHOLTANDHEETHTHETENDRECR
OPPESANDTHEYONGESONNEHATHINTHERAMHI
SHALVECOURSYRONNEANDSMALEFOWELESMAK
ENMELODYETHATSLEPENALTHENYGHTWITHOP
ENYESOPRIKETHHEMNATUREINHIRCORAGEST
HANNELONGENFOLKTOGOONONPILGRIM
The Challenge:
Write a function to decrypt the cipher.

The output does not need line breaks or spaces.

Input is has no line breaks or spaces.

Shortest solution wins.

(Bonus points if you can solve the other 2 ciphers :P)

My attempt (PHP 77 70):
$b=strrev($a);for($i=0;$i<5;$i++)for($j=0;$j<381;$j++)$r.=$b[$i+$j*5];

*/

#include <assert.h>
#include <stdio.h>
#include <string.h>

char *
decrypt(const char *s, size_t n, char *b)
{
	size_t i, j, k, l;

	l = 0;
	for (i = 0; i < 5; i++) {
		j = (i < n) ? n - i : n;
		for (; j > 0; j -= k) {
			b[l++] = s[j - 1];
			k = (j < 5) ? j : 5;
		}
	}
	b[l] = '\0';

	return b;
}

void
test(const char *s, const char *r)
{
	char b[512];

	decrypt(s, strlen(s), b);
	printf("%s\n", b);
	assert(!strcmp(b, r));
}

int
main(void)
{
	static const char cipher[] =
	    "MEOTAIHSIBRTEWDGLGKNLANEAINOEEPEYST"
	    "NPEUOOEHRONLTIROSDHEOTNPHGAAETOHSZO"
	    "TTENTKEPADLYPHEODOWCFORRRNLCUEEEEOP"
	    "GMRLHNNDFTOENEALKEHHEATTHNMESCNSHIR"
	    "AETDAHLHEMTETRFSWEDOEOENEGFHETAEDGH"
	    "RLNNGOAAEOCMTURRSLTDIDOREHNHEHNAYVT"
	    "IERHEENECTRNVIOUOEHOTRNWSAYIFSNSHOE"
	    "MRTRREUAUUHOHOOHCDCHTEEISEVRLSKLIHI"
	    "IAPCHRHSIHPSNWTOIISISHHNWEMTIEYAFEL"
	    "NRENLEERYIPHBEROTEVPHNTYATIERTIHEEA"
	    "WTWVHTASETHHSDNGEIEAYNHHHNNHTW";

	static const char text[] =
	    "WHANTHATAPRILLEWITHHISSHOURESSOOTET"
	    "HEDROGHTEOFMARCHHATHPERCEDTOTHEROOT"
	    "EANDBATHEDEVERYVEYNEINSWICHLICOUROF"
	    "WHICHVERTUENGENDREDISTHEFLOURWHANZE"
	    "PHIRUSEEKWITHHISSWEETEBREFTHINSPIRE"
	    "DHATHINEVERYHOLTANDHEETHTHETENDRECR"
	    "OPPESANDTHEYONGESONNEHATHINTHERAMHI"
	    "SHALVECOURSYRONNEANDSMALEFOWELESMAK"
	    "ENMELODYETHATSLEPENALTHENYGHTWITHOP"
	    "ENYESOPRIKETHHEMNATUREINHIRCORAGEST"
	    "HANNELONGENFOLKTOGOONONPILGRIM";

	test(cipher, text);

	return 0;
}
