/*

You are given two strings s and t.

String t is generated by randomly shuffling string s and then adding one more letter at a random position.

Return the letter that was added to t.

Examples

findTheDifference("", "e") ➞ "t"

findTheDifference("abcd", "abcde") ➞ "e"

findTheDifference("rt", "rst") ➞ "s"

findTheDifference("gjklmn", "ghjklmn"") ➞ "h"

findTheDifference("ae", "aea") ➞ "a"

Notes

N/A

*/

fn diff(s: &str, t: &str) -> char {
    let mut r = 0;
    for c in s.chars() {
        r ^= c as u8;
    }
    for c in t.chars() {
        r ^= c as u8;
    }
    return r as char;
}

fn main() {
    assert_eq!(diff("bcefg", "bcdefg"), 'd');
    assert_eq!(diff("bcdfg", "bcdefg"), 'e');
    assert_eq!(diff("aiou", "aeiou"), 'e');
    assert_eq!(diff("mnoqrst", "mnopqrst"), 'p');
    assert_eq!(diff("rsuvw", "rstuvw"), 't');
    assert_eq!(diff("abcd", "abcde"), 'e');
    assert_eq!(diff("rt", "rst"), 's');
    assert_eq!(diff("gjklmn", "ghjklmn"), 'h');
    assert_eq!(diff("ae", "aea"), 'a');
}
