/*

The function is given two strings $t - template, $s - to be sorted. Sort the characters in $s such that if the character is present in $t then it is sorted according to the order in $t and other characters are sorted alphabetically after the ones found in $t.

Examples

customSortt("edc", "abcdefzyx") ➞ "edcabfxyz"

customSortt("fby", "abcdefzyx") ➞ "fbyacdexz"

customSortt("", "abcdefzyx") ➞ "abcdefxyz"

customSortt("", "") ➞ ""

Notes

The characters in $t and $s are all lower-case.

*/

package main

import (
	"sort"
)

func main() {
	assert(customsort("edc", "abcdefzyx") == "edcabfxyz")
	assert(customsort("fby", "abcdefzyx") == "fbyacdexz")
	assert(customsort("", "abcdefzyx") == "abcdefxyz")
	assert(customsort("", "") == "")
	assert(customsort("cteqh", "xnjanztmhg") == "thagjmnnxz")
	assert(customsort("jv", "cxkafinfiuhnnaracsztbrcwaifwattzavwohoqskauififucq") == "vaaaaaaabccccfffffhhiiiiikknnnooqqrrsstttuuuwwwxzz")
	assert(customsort("xtz", "uhgpqydzwtsemucfidpvrvormgfjefpqeprvmyiazqokmnhdwvyglngcsriw") == "tzzaccdddeeefffgggghhiiijklmmmmnnooppppqqqrrrrssuuvvvvwwwyyy")
	assert(customsort("eyuti", "iuanyojxqbmihzyvjunb") == "yyuuiiabbhjjmnnoqvxz")
	assert(customsort("ndgi", "eqfbnjbpbisjoakfnncpaphvvzxsodaw") == "nnndiaaabbbceffhjjkoopppqssvvwxz")
	assert(customsort("ymd", "duoisjfobwlztxsaymzjwvpofouyijglwgvogpt") == "yymdabffgggiijjjlloooooppssttuuvvwwwxzz")
	assert(customsort("wpkmv", "crcasndkumqcckmqxcpagkjveovcmnmzvbkixeduqohkutbelm") == "pkkkkkmmmmmvvvaabbccccccddeeeghijlnnooqqqrstuuuxxz")
	assert(customsort("qdmbfc", "mruwsotaydpzeezpgmmcrhbwsihrbzryqheigapvaehnyjgvbvqrdxtqkczujzqngpdmrduffcokcnfcqqmqtwbquzssalydifip") == "qqqqqqqqdddddmmmmmbbbbffffcccccaaaaeeeegggghhhhiiiijjkklnnnooppppprrrrrrsssstttuuuuvvvwwwxyyyyzzzzzz")
	assert(customsort("iupmz", "ixavjrmbwacgwvxcrauvcfcizfoxxabdyossqvzubqnpdzphbpurikqzqigjdrjsycpjlpstokvnijpcchcgtdfvqkltbdqidptvbsmwxeuqxyvcyzfiksnrrzbpmxdlhzieocmabqszqanfwjqmjb") == "iiiiiiiiuuuuppppppppmmmmmzzzzzzzzaaaaaabbbbbbbbbccccccccccdddddddeefffffggghhhjjjjjjjkkkklllnnnnooooqqqqqqqqqqrrrrrrsssssssttttvvvvvvvvwwwwxxxxxxxyyyy")
	assert(customsort("cjhfnu", "uokmxyzaisghuqmxxhnntlhhasjwfkjutdoumlkwfusscjspauroihkxmsvamxuqronfszjmgnqjlwdkvndslsykrojvrienrhtrvtrmacuneouorbjceadhskonhbnghctqbqkgzqwuaegumugggilhjbzqcpgbpkfxlbeyinfdrzkvesxjnmyvrwbftuymtzrzzzlm") == "cccccjjjjjjjjjhhhhhhhhhhffffffnnnnnnnnnnnuuuuuuuuuuuuuaaaaaaabbbbbbbdddddeeeeeegggggggggiiiiikkkkkkkkkklllllllmmmmmmmmmmmoooooooopppqqqqqqqrrrrrrrrrrrssssssssssstttttttvvvvvvwwwwwxxxxxxxyyyyyzzzzzzzzz")
	assert(customsort("novctmix", "hufppxpeisstygylmfwgfftwagpnkzqzcizntyejrvsfxxavvezdsddcdkgogkgkqkuexycbqzdicpxdqjdyncgmiatdbshrzcdfmxyanudnynwdhunfjqqccnncolkpcylkivehdaejlndoldmwbtibzcfsvpvmbyweviedadrqjnukmemjbwpefwhuonpdysivbeybmejzcjmswrpmgieffmpsfxkmmojklnqpelfrcaojcpouzkctajfwvgddcflfksscuwopqrjyqwghnwgblavhztnaeyqgebjodyte") == "nnnnnnnnnnnnnnnooooooooovvvvvvvvvvcccccccccccccccccttttttttmmmmmmmmmmmmmiiiiiiiiixxxxxxxaaaaaaaaaabbbbbbbbbbddddddddddddddddddddeeeeeeeeeeeeeeeeeffffffffffffffffgggggggggggghhhhhhhjjjjjjjjjjjjjkkkkkkkkkkkklllllllllppppppppppppppqqqqqqqqqqqrrrrrrsssssssssssuuuuuuuuwwwwwwwwwwwwyyyyyyyyyyyyyyzzzzzzzzzz")
	assert(customsort("thvuybo", "ahharlbhljltdsfdnosejlfqjiagscjzaeohishxlclidyjwujukzjosfnwafvpmifsuuefnxgxjptayqqdidesuxbdbeljravainxgqddujcrwgawdqrhzoesozymihqktdkbhwmtxyoaawgilobdpfdissmmbomfzmogjnrbwrtwaxditdnivjfajpfuoozoyaplurcmodmtfvlnxmhhmygtpxgaxsgfpynppmjbklckosakqejqcmmhbaagpwryflomemizdlfcecslcqdtwyjjksavdbzimziqiloagxebqygirghyjmiaxzyoweadutohctkmwruxpnobfoglrksfxxyk") == "ttttttttttthhhhhhhhhhhhhvvvvvuuuuuuuuuuyyyyyyyyyyyyybbbbbbbbbbbbooooooooooooooooooooaaaaaaaaaaaaaaaaaaaaaaccccccccccdddddddddddddddddddeeeeeeeeeeeffffffffffffffffggggggggggggggiiiiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjjkkkkkkkkkkllllllllllllllllmmmmmmmmmmmmmmmmmmmnnnnnnnnnpppppppppppqqqqqqqqqqqrrrrrrrrrrrssssssssssssssswwwwwwwwwwwwxxxxxxxxxxxxxxxzzzzzzzzzz")
	assert(customsort("pgjiyhkor", "ctocsybgtvhbobisqhxicddaiykrlyfzegnmytpuomrwybvaqcuigzehqnizepqjyamnraqprghctzxdgufqrwjfskjfyonwtbqhtjnhtqzarwawjprdckbezvvolbtcrubnpvstaaiytphclyfzxrajvailyvhnxjrwarccndmefmygpkjlurgnrijyfglcicvfgysgptqlnuqfybscgjqbufiqzpixerftznkixownsmmoqhhcfuacwmahcuxgnvvawzktcjzyofmpxbgxrmjeabkknkbkterkaqdtrekmfoleyhikdcnwnkiyacxquhyvuwdrralwypvbwmhorsvoghtjnsavtbiefeif") == "pppppppppppggggggggggggggjjjjjjjjjjjjjiiiiiiiiiiiiiiiiyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhkkkkkkkkkkkkkkooooooooooorrrrrrrrrrrrrrrrrrrraaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbcccccccccccccccccccddddddddeeeeeeeeeeeefffffffffffffffflllllllllmmmmmmmmmmmmnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqssssssssstttttttttttttttttuuuuuuuuuuuvvvvvvvvvvvvvvwwwwwwwwwwwwwxxxxxxxxxxzzzzzzzzzzz")
	assert(customsort("jxrqklbgut", "qdjufpwzuttywfbcviuyreqgmwlnejsgbapgbybohkyflajcmhikdpzszwbsmfgcbhmtxwofgjjkvcednyyphusnzvahpeaoqsshhgjslpybwzambbuwbkpnkrnpmetqfuytmhbrousmsuuinvnrlmerfdunixycgmtslmrervxmsekkrdcznyykghhdzmhwnzycqxwzolqnswwmukpxikuklwqqhkgxlknqjtpigvoivwnymxxjmikvklafgkibreppwwkwffxixgjxheyornboevxnqslwpxjeaagqvcdhytirdxyaypghxbqpodwrrgyovsgcjrealijagpeiklkbzlpskkratjnoowdpunvfdmgjsitasevwjxrnyjoexhhgrgizoyszuzosaaxugpaopkpqrpkxbchygmovixndcggrvnjxazuphbztcumvntlqrxihojlkiwydtabdnhxjedbnircuwzbbikguyjucwuqwvohb") == "jjjjjjjjjjjjjjjjjjjjxxxxxxxxxxxxxxxxxxxxxxxrrrrrrrrrrrrrrrrrrrrrqqqqqqqqqqqqqqqkkkkkkkkkkkkkkkkkkkkkkkkklllllllllllllllbbbbbbbbbbbbbbbbbbbbbbggggggggggggggggggggggggguuuuuuuuuuuuuuuuuuuuutttttttttttttaaaaaaaaaaaaaaaaaaccccccccccccccdddddddddddddddeeeeeeeeeeeeeeeeefffffffffffhhhhhhhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiiiimmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnnnooooooooooooooooooopppppppppppppppppppppppsssssssssssssssssssvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzz")
	assert(customsort("vupdsfgrxkob", "qqxaqgcnyxpskszwdgcfziyhamuursywnpyagjeffyiiduegqxyjvjgbifixwlrcdhhlnviurfuwqzdvoxqlrxhzncaovazhsiovnutkroznckeuawhlamsvvpmrvpdnovzmtrnyohgybsemqzcxlcwryqfeseqxkqqdqqhholzssrqsrnswqgqteajockivqqkjmmafdkswbduaelhqqbmslrygrudswaziadrdwfmicnmdtmrwgxmuxipmnjbhdobbknepdewivqwnfdxnkzdzdtgcbafvjgaolbptzfjexjkbgrsajmcgyeivgneyyltfgaeqgzzmtfkkokfhwdhvmhhemcnfngjgjupjgcwtmtzuuvsexrhbzqxlfwfyeswevyetwpwmfvmhwrvgjxbgkarinrqavoeeujkthnoimatblovywbkjkwqijkkxizlrpqqsmqwaitwrgmrxcaipshowtkmecmigwufqsqxbjdyntvcpgfqcbmnjlvvftecppcdfecsbkulqozslpybgzfuyjlfldokvrkeqikxjpszdtoebwwekbfemrxlbcqsvpopzqabixdrhfeyiqtkh") == "vvvvvvvvvvvvvvvvvvvvvvvvvuuuuuuuuuuuuuuuuuppppppppppppppppppdddddddddddddddddddddddssssssssssssssssssssssssffffffffffffffffffffffffffgggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeehhhhhhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjjjjjlllllllllllllllllllmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqtttttttttttttttttttwwwwwwwwwwwwwwwwwwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzz")
	assert(customsort("opdzsivgarylwut", "alvvrdrpodmnqtlvmzbacxvxdmewsianihbdhnbiwhdzxnpkzvanawjkcqszvlslhxuanzdswpfvutldiwvskctbxzapqjvrfnymebzvqmvprtrmjgngzwpcdxmjkvbfuzyjrlvyizvbqcffjizgcyqkggzocifneiwkcwvdxzhdrjcrnrjdugnhzfpnmoxbczbqrupyyrumlbetwzaualwykciqxllxuermbdphxjwprprvmehowzxtyagrlezarcxwywgezsxxnwxdrmwoaakksfxipklmghcxltsncwqwnivztepxgjnwhizufgfakswgcqykysqiucwveponhvunirxwtmafbfrugnntjhadqggnerfkxfpipxpxeruauaaexvzxsonopkxeaxmachfxjjdtoxutrqvgydvevtjwltkxeiggxkhbecsqigqfqjqazfncbgxalbzsxpksvlvtqqwcvnqpvnqvfqqnufdojpjomsbpalfnwbrtdvhetvxdjpnxoftlplthcdfgzlzqsdooiacopqsjumjmnbqeuspusrpbpxnxgfxnqdlstxmfczqburziytvkcxdskkzkrisxycrtlpaathgiligmgywbnmynkumhmovagynbrlvljubifkwivrqhsykamixhhvdfngauifhwpkziutxqoqngsjbjcklrultvjshkmpmlchflzpgmvgrzkqsrxmicikvbgbzmmypzzbcndxjpqejhhktvngzqtlwiuhqjnanqqpgnlfvogchjzsqwtsdwljqvjqazhpuhxyhwzpofembzxdofktxeozijzfocewsojmrpgcamplqfsdxbognpdtkxpogqanlvzmicgfrnkgwwwvsxfpaywesmysmqqsny") == "oooooooooooooooooooooooooppppppppppppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzssssssssssssssssssssssssssssssssssiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvgggggggggggggggggggggggggggggggggggggggaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyllllllllllllllllllllllllllllllllllwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwuuuuuuuuuuuuuuuuuuuuuuuuuuuttttttttttttttttttttttttttttttbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeefffffffffffffffffffffffffffffffffffhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
}

func customsort(t, s string) string {
	m := make(map[rune]rune)
	n := rune(0)
	for _, r := range t {
		m[r], n = n, n+1
	}
	for r := 'a'; r <= 'z'; r++ {
		_, f := m[r]
		if !f {
			m[r], n = n, n+1
		}
	}

	p := []rune(s)
	sort.Slice(p, func(i, j int) bool {
		x, f := m[p[i]]
		y, g := m[p[j]]
		if !f {
			x = p[i]
		}
		if !g {
			y = p[j]
		}
		return x < y
	})

	return string(p)
}

func assert(x bool) {
	if !x {
		panic("assertion failed")
	}
}
